/**
 * Generated by tsnapi — public API snapshot of `lz-string-es`
 */
// #region Functions
export declare function _compress(_: null, _: number, _: (_: number) => string): "";
export declare function _compress(_: string, _: number, _: (_: number) => string): string;
export declare function _decompress(_: number, _: number, _: (_: number) => number): string | null | undefined;
export declare function compress(_: string | null): string;
export declare function compressToBase64(_: string | null): string;
export declare function compressToCustom(_: string | null, _: string): string;
export declare function compressToEncodedURIComponent(_: string | null): string;
export declare function compressToUint8Array(_: string | null): Uint8Array;
export declare function compressToUTF16(_: string | null): string;
export declare function convertFromUint8Array(_: Uint8Array): string;
export declare function convertToUint8Array(_: string | null, _?: boolean): Uint8Array<ArrayBuffer> | null;
export declare function decompress(_: string | null): string | null | undefined;
export declare function decompressFromBase64(_: string | null): string | null | undefined;
export declare function decompressFromCustom(_: string | null, _: string): string | null;
export declare function decompressFromEncodedURIComponent(_: string | null): string | null | undefined;
export declare function decompressFromUint8Array(_: Uint8Array | null): string | null;
export declare function decompressFromUTF16(_: string | null): string | null | undefined;
// #endregion

// #region Variables
export declare const _lzStringOriginalVersion: string;
// #endregion